### ISSUE TITLE
Undefined method `delete_prefix` for String

### ISSUE THREAD

**Issue by nikomikulicic** [rccavalcanti/fyodor#1] opened 2020-01-07 21:46 UTC
Hi there,

first of all, thank you for this effort. It was always a nightmare getting notes from personal docs.

However, I still haven't managed to successfully run it. Here's the issue I've encountered:
```undefined method `delete_prefix` for #<String:0x00007f8e6081d198>```

I've attached simplified version of `My Clippings.txt` which still produces this error
[My Clippings test.txt](https://github.com/rccavalcanti/fyodor/files/4032595/My.Clippings.test.txt)

Any help is appreciated

**Comment by rc2dev** [comment] 2020-01-07 22:28
Hi Niko,

Thanks for the words!

Can you check your Ruby version with `ruby -v`? `String#delete_prefix` was added on Ruby 2.5, so that's probably the cause.

**Comment by nikomikulicic** [comment] 2020-01-08 16:06
You're right about the ruby version. I've updated it now using instructions from: https://stackoverflow.com/questions/38194032/how-to-update-ruby-version-2-0-0-to-the-latest-version-in-mac-osx-yosemite

`ruby -v` now prints: `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]`

I tried running fyodor again:
```
/Library/Ruby/Site/2.3.0/rubygems.rb:275:in `find_spec_for_exe': can't find gem fyodor (>= 0.a) with executable fyodor (Gem::GemNotFoundException)
	from /Library/Ruby/Site/2.3.0/rubygems.rb:252:in `bin_path'
	from /usr/local/bin/fyodor:22:in `<main>'
```
I figured I maybe messed something up with homebrew so I reinstalled fyodor and now it prints: 
```
Ignoring executable-hooks-1.6.0 because its extensions are not built. Try: gem pristine executable-hooks --version 1.6.0
Using config at /Users/nikomikulicic/.config/fyodor.toml

undefined method `delete_prefix' for #<String:0x00007ff10011ef60>
```

I also tried executing `gem pristine executable-hooks --version 1.6.0`
```
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["executable-hooks"] = 1.6.0
```

So I guess I'm stuck again. :)

**Comment by rc2dev** [comment] 2020-01-08 19:55
On your first output, Ruby was searching your system 2.3 directory, instead of RVM's 2.6. Later, it gave `undefined delete_prefix` which means you were running Ruby < 2.5. 

So it looks like your RVM installation isn't working well.

Try running 
```
rvm use 2.6
gem install fyodor
fyodor
```

If the first command fails, RVM is probably not being sourced to your shell. Take a look at [RVM documentation](https://rvm.io/).

I'm closing this issue and adding a dependency for Ruby >=2.5 on the gem.

**Closed as completed** 2020-01-08 19:56 UTC
