### ISSUE TITLE
Similar highlights not being deleted

### ISSUE THREAD

**Issue by mbmbmbm** [rccavalcanti/fyodor#2] opened 2020-05-12 11:19 UTC
Hi Rafael,

This is great - the basic parsing and generation of .md files works perfectly. I am finding that partial duplicates aren't being deleted, though. By that I mean, if I highlight something and then edit by changing the start/end point of the highlight, it doesn't detect that the highlights are basically the same.

I get the following result:

We couldn't *improve* the output of 45 (83.3%) entries.
Possible causes:
- Wrong strings in the config file (most probable).
- Your locale has some specificity the app is not aware. Please open an issue.
- Your clippings file has more than one locale.

I have no programming experience, so I may well be missing something. I installed Ruby 2.6.6 using the windows installer and followed your instructions. I've attached an example of the output here.

Thanks,
Mitch

[Ellison, Harlan - ﻿Dangerous Visions (S.F. MASTERWORKS).md.txt](https://github.com/rccavalcanti/fyodor/files/4615191/Ellison.Harlan.-.Dangerous.Visions.S.F.MASTERWORKS.md.txt)

**Comment by rccavalcanti** [comment] 2020-05-12 22:48
Hi Mitch,

For your first question:

Partial duplicates aren't filtered by Fyodor. I considered implementing that, but the detection and the selection of which sentence is kept is tricky for a number of reasons.

For now, Fyodor removes exact duplicates. It even checks that both highlights are from the same position on the book.

**Comment by rccavalcanti** [comment] 2020-05-12 22:51
About the output you get:

- Is in your clippings file (or Kindle) in English?
- Can you attach a copy of it? No need to attach it fully. I only need some entries to check the locale strings.

**Comment by rc2dev** [comment] 2020-05-12 23:01
Hi Mitch,

**For your first question:**

Partial duplicates aren't filtered by Fyodor. I considered implementing that, but the detection and the selection of which sentence is kept is tricky for a number of reasons.

For now, Fyodor removes exact duplicates. It even checks that both highlights are from the same position on the book.

**About your output:**

The output you attached was correctly parsed.

That message means that Fyodor couldn't understand some strings on your clippings file, so it couldn't generate nicer markdowns for you (with less duplicates, better formatting, etc).

Is your clippings file fully in English?
Would you mind attaching it so I can take a look?

**Comment by mbmbmbm** [comment] 2020-05-13 00:08
Hi Rafael,

Ah okay, I thought that might be the case regarding duplicates. I had thought it might take the most recent version of a similar sentence, but I realise it's not as simple as that. 

The clippings file is fully in English. I did try editing the config file to match the clippings file by changing 'Location' to 'location', but got similar results.

I've attached an edited copy here with one annotation from each library item. Some of them are PDFs in case that makes a difference, but they also seem to be working fine.

As it is the program works great, and manually cleaning up the output isn't a huge job anyway. Thanks very much for the response, will buy you a coffee!

[My Clippings-edited.txt](https://github.com/rccavalcanti/fyodor/files/4619027/My.Clippings-edited.txt)

**Comment by rc2dev** [comment] 2020-05-13 00:25
Yes, keeping the newer wouldn't work. Think of this scenario:

1. User highlights text "foobar 1".
2. User highlights similar text "foobar 2".
3. User regrets the newer highlight and deletes it, keeping the older.

Now in the clippings file we'll have both similar highlights, "foobar 1" and "foobar 2". Should Fyodor keep the newer ("foobar 2")? No.

The problem is that the Kindle only gives us so much information in the clippings file. It doesn't tell us if a highlight was deleted, modified, etc, so we can only do so much cleaning before starting to guess, or implementing a somewhat complex logic.

Thanks for the clippings file! The only difference about the strings on it is that "Location" is lowercased to "location". Changing this on my configuration fixes the parsing for those entries. 

For the other highlights, it's a different problem. They only have their page number, not their location. That's different from what I've seen until now. So I'll have to update Fyodor accordingly, since it assumes that syntax.

Btw, thanks for the coffee! Very much appreciated.

Edit: Merged the two comments and minor fixes.

**Comment by rccavalcanti** [comment] 2020-05-13 00:47
Besides the capitalization, there is a second problem.

Two of those highlights only have their page number, not their location.

That's different from what I've seen until now. So I'll have to update Fyodor accordingly, since it assumes that syntax for some goals.

Thanks for reporting!

**Comment by rc2dev** [comment] 2020-05-13 02:47
I just released a new version with both fixes.

Can you please check that the problem is gone?

Update Fyodor with `gem update fyodor --no-doc` and then try to run it again.

**Comment by mbmbmbm** [comment] 2020-05-14 08:30
> Yes, keeping the newer wouldn't work. Think of this scenario:

Yep, that makes sense.

> Can you please check that the problem is gone?

Yep, working perfectly now:

6 books found
Ignored 0 empty and 9 duplicated entries.
Highlights: 81
Notes: 3
Bookmarks: 0
Clips: 0
Unrecognized: 0
-------------------
TOTAL: 84

ALL entries were correctly parsed.

> Btw, thanks for the coffee!

Pleasure, thanks again for your work on this!

**Comment by rc2dev** [comment] 2020-05-14 13:22
Great! Closing the issue.

**Closed as completed by rc2dev** 2020-05-14 13:22 UTC

**Comment by opatotto** [comment] 2022-10-16 06:26
I have the same problem with Similar highlights, I think this can be solved adding a condition in the configuration to activate this functionality of last coincidence, the logic could be something like...

*Remove repeated from the beginning
Compare first number of highlighted position with another in the file is equals, then check if the first 2 words are the same in the highlighted text with the coincidence found, leave the part with the most recent date and delete the others.

*Remove repeated at the end
Compare second number of highlighted position with another in the file is equals, then check if the last 2 words are the same in the highlighted text with the coincidence found, leave the part with the most recent date and delete the others.

I think this will solve the problems of similar highlights, hope this can help to improve the code, cheers!!

**Comment by rc2dev** [comment] 2022-10-16 13:15
Hi @opatotto,

Consider the following:

> I read books daily. I read magazines mostly in the evening.

And the respective highlights:

- I read books daily. highlight @ position 100
- I read magazines mostly in the evening. highlight @ position 100

Your algorithm would _mistakenly_ delete the first highlight. Besides that, there are books - as the one mentioned in this issue - that doesn't even have position information, only pages.

As I said, without more data from the clippings file, such as a more fine grained position information, or a deleted flag, we can't do this without adding code complexity and risking false positives.

**Comment by opatotto** [comment] 2022-10-17 00:09
Hi @rc2dev,

I analyzed my highlights and know about about it, that's why I added this condition to solve this problem:

> then check if the first 2 words are the same in the highlighted text with the coincidence found

Maybe 5 words should be enough to be safer, In my research (20 books highlights tested) I only found a coincidence on the first two word within the same position that match your example, most of the time is the same word at first position that refers the same highlight. 

This should work also for pages instead of position, this could be an optional not default configuration, for most of users I think this can solve the problem, I understand that some information is missing to detect some variables but you can test this algorithm to see if it works on your highlights.

I'm not familiar with ruby, I don't know if this could be difficult, I hope this can help this project.

There is another approach to solve this problem using regex using this:

`^(\S+) (?=(?s:.)*(\1.*)).*`

I noticed under group 2 select the repeated ones but there are others repeated not selected. This could also be a solution.

You can test the regex here https://regex101.com/

**Comment by rc2dev** [comment] 2022-10-17 02:54
My point still stands, and I'm not interested in developing and maintaining such heuristics, but thanks for your input.

To add in:

Also keep in mind that there are many different literary styles, hundreds of languages (dead and alive), and each person highlights a book or a document in his own style.

Note that even for you your algorithm failed at least once. Now add all those variables, and you can have an idea of the endeavor of developing such a filter.
